# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform OAuth2-Proxy installation tasks
  when: oauth2_proxy_enabled | bool
  tags:
    - setup-all
    - setup-oauth2-proxy
    - install-all
    - install-oauth2-proxy
  block:
    - name: Validate OAuth2-Proxy configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install OAuth2-Proxy
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform OAuth2-Proxy uninstallation tasks
  when: not oauth2_proxy_enabled | bool
  tags:
    - setup-all
    - setup-oauth2-proxy
  block:
    - name: Uninstall OAuth2-Proxy
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
