# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform OAuth2-Proxy installation tasks
  block:
    - name: Validate OAuth2-Proxy configuration
      when: oauth2_proxy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install OAuth2-Proxy
      when: oauth2_proxy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-oauth2-proxy
    - install-all
    - install-oauth2-proxy

- name: Perform OAuth2-Proxy uninstallation tasks
  block:
    - name: Uninstall OAuth2-Proxy
      when: not oauth2_proxy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-oauth2-proxy
